### ISSUE TITLE
Couldn't launch tortoisebotpromax_playground.launch

### ISSUE THREAD

**Issue by MukilSaravanan** [rigbetellabs/Robonautica#1]
Hi, 
I am using ROS Noetic on Ubuntu 20.04. 
I followed the steps as mentioned in the README file.  The source code and dependencies got build successfully. 
When I try launching the tortoisebotpromax_playground.launch file, I face the below error

`... logging to /home/mukil/.ros/log/b4abd1b6-6616-11ee-a282-5be075ffd1d1/roslaunch-mukil-ubuntu-Dell-G15-5515-12098.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:33753/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.15.15
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [12118]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b4abd1b6-6616-11ee-a282-5be075ffd1d1
process[rosout-1]: started with pid [12139]
started core service [/rosout]
process[spawn_urdf-2]: started with pid [12142]
process[joint_state_publisher-3]: started with pid [12146]
process[robot_state_publisher-4]: started with pid [12148]
process[gazebo-5]: started with pid [12149]
process[gazebo_gui-6]: started with pid [12154]
**[ERROR] [1696795821.366083727]: material 'silver' is not unique.**
[robot_state_publisher-4] process has died [pid 12148, exit code 1, cmd /opt/ros/noetic/lib/robot_state_publisher/robot_state_publisher __name:=robot_state_publisher __log:=/home/mukil/.ros/log/b4abd1b6-6616-11ee-a282-5be075ffd1d1/robot_state_publisher-4.log].
log file: /home/mukil/.ros/log/b4abd1b6-6616-11ee-a282-5be075ffd1d1/robot_state_publisher-4*.log
sh: 1: prefix: not found
sh: 1: prefix: not found
sh: 1: prefix: not found
sh: 1: prefix: not found
[librospack]: error while executing command
sh: 1: prefix: not found
sh: 1: prefix: not found
sh: 1: prefix: not found
sh: 1: prefix: not found
[librospack]: error while executing command
[ INFO] [1696795821.957544867]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1696795821.958752246]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1696795822.034965110]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1696795822.037122035]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1696795822.619338169]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1696795822.635754103]: Physics dynamic reconfigure ready.
**[ERROR] [1696795822.667720, 2771.836000]: Spawn service failed. Exiting.
Error [parser_urdf.cc:3183] Unable to call parseURDF on robot model
Error [parser.cc:488] parse as old deprecated model file failed.**
[spawn_urdf-2] process has died [pid 12142, exit code 1, cmd /opt/ros/noetic/lib/gazebo_ros/spawn_model -param robot_description -urdf -model tortoisebotpromax -x 0.0 -y 0.0 -z 0.05 __name:=spawn_urdf __log:=/home/mukil/.ros/log/b4abd1b6-6616-11ee-a282-5be075ffd1d1/spawn_urdf-2.log].
log file: /home/mukil/.ros/log/b4abd1b6-6616-11ee-a282-5be075ffd1d1/spawn_urdf-2*.log`

Thanks in advance.

**Comment by ShubhamNandi** [comment]
Please take the new pull have fixed the dependencies issues for realsense

**Comment by MukilSaravanan** [comment]
Thanks for your help @ShubhamNandi
