### ISSUE TITLE
Facing issue while launching tortoisebotpromax_playground.launch

### ISSUE THREAD

**Issue by yashphalle** [rigbetellabs/Robonautica#2]
Hii,
I was trying to launch tortoisebotpromax_playground.launch
I can see the gazebo window with the arena but unable to launch the bot in it. 
I was getting this error while launching I think this might be due to a clash in dependencies or something 
If possible, can someone help me out with this?
Thanks!
Attaching terminal output image for reference
![WhatsApp Image 2023-10-09 at 12 39 23 PM (1)](https://github.com/rigbetellabs/Robonautica/assets/82230267/1d542080-68e2-4085-80f6-e6f525a29e7d)

**Comment by ShubhamNandi** [comment]
Have fixed the realsense dependencies issues please take the pull for the latest updates

**Comment by yashphalle** [comment]
Thank You @ShubhamNandi Sir!
