### ISSUE TITLE
Missing odom frame

### ISSUE THREAD

**Issue by maker-ATOM** [rigbetellabs/Robonautica#3]
After executing the following two commands in different terminal,
`roslaunch tortoisebotpromax_gazebo tortoisebotpromax_playground.launch`

`roslaunch tortoisebotpromax_description display.launch`

To generate a map of the environment, odom frame was found to be missing. Only the odom topic exists where gazebo publishes the data.

This is the tf_tree displayed by the rqt tool.
![frames](https://github.com/rigbetellabs/Robonautica/assets/87944335/7708f290-5246-4c5c-b5ea-c9cf466053fc)

This is the tf_tree displayed by rviz
![Screenshot from 2023-10-09 12-53-50](https://github.com/rigbetellabs/Robonautica/assets/87944335/2badf4a2-0f58-4575-9133-184886cde315)

Available frames recognized by rviz.
![Screenshot from 2023-10-09 12-54-35](https://github.com/rigbetellabs/Robonautica/assets/87944335/29abf655-77ce-405a-be13-c222841e4300)

**Comment by ShubhamNandi** [comment]
are you able to echo data on the /odom topic and is there data available?

**Comment by ShubhamNandi** [comment]
Fixed the Odom frame!
Please take a pull for the updates
